### ISSUE TITLE
Please show with an example, I am not able to under stand how to Pass the URL and credentials in that script

### ISSUE THREAD

**Issue by ramakrishnagith** [MarcusFelling/PowerShell#1]
Please show with an example, I am not able to under stand how to Pass the Azure Devops URL and credentials in that script

**Comment by MarcusFelling** [comment]
@ramakrishnagith Are you referring to TFS_CreateBranchPolicies.ps1? That script uses environment variables to form the URL ($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI + $env:SYSTEM_TEAMPROJECT) so it doesn't need to be set. I execute most of these scripts in a pipeline, so the agent picks up the environment variable values. All of my scripts use personal access tokens (PAT) that are usually stored as secret variables in a build or release definition. You can read more on PAT's here: https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops
